config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root to:'homes#top'
  get "home/top" => "homes#top"
  get "home/about" => "homes#about"
  resources :users, only: [:show, :edit, :update, :index]
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update]do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
    resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member 
    get :followers, on: :member 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    end
     validates :title, presence: true
     validates :body, presence: true, uniqueness: true,
                      length: { maximum: 200 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :books, dependent: :destroy
   has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
   validates :name, presence: true, uniqueness: true,
                      length: { minimum:2, maximum: 20 }
  validates :introduction, length: { maximum: 50}
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  def followed_by?(user)
   passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 before_action :authenticate_user!
 before_action :ensure_correct_user, only: [:update, :edit]

def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
    @post_comment = PostComment.new
end

def edit
    if params[:id] == current_user.id
         @user = User.find(params[:id])
    render action: :edit
    else
    @user = current_user
    render action: :show
    end
  @book= Book.find(params[:id])
end

def update
    @book = Book.find(params[:id])
    if @book.update(book_paramas)
    redirect_to book_path(@book), notice: 'You have updated book successfully.'
    else
        render :edit
    end
end

def create
    @book = Book.new(book_paramas)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
        @books = Book.all
        @user = current_user
        render :index
    end
end

def  index
    @books = Book.all
    @user = current_user
    @book = Book.new
    
end

def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to action: "index"
end

private
def book_paramas
    params.require(:book).permit(:title, :body)
end

 def ensure_correct_user
    @book = Book.find_by(id:params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
 end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    PostComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

private
    def post_comment_params
    params.require(:post_comment).permit(:comment)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to users_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :authenticate_user!
 before_action :ensure_correct_user, only: [:update, :edit]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book=Book.new
    @books=@user.books
  end


  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
        render :edit
    end
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :opinion, :profile_image)
  end
 def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
 end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
<div class="profile-container">
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:"100x100" %>
  <table class="table">
  <tr>
      <th>
      <div class="profile-name">name
      </th>
      <th><%= user.name %></div>
     </th


  </tr>
  <tr>
      <td>
  <divclass="profile-introduction">introduction
      </td>
      <td><%= user.introduction %></div>
      </td>
      <td><p><%=link_to "フォロー", follows_user_path(@user.id) %></p></td>
      <td><p><%=link_to "フォロワー", followers_user_path(@user.id) %></p></td>
<% if current_user != @user %>
    <% if @user.followed_by?(current_user) %>
        <p><%=link_to "フォロー済み", user_relationships_path(@user.id), method: :delete %></p>
    <% else %>
        <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
    <% end %>
<% end %>
  </tr>
  </table>
  </div>

    <p><%= link_to edit_user_path(user) do %>
   <i class="btn btn-outline-secondary btn-block fas  fa-user-cog"></i>
   <% end %></p>


<h4>New book</h4>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:book,local:true do |f| %>
<p>Title</p>
 <%= f.text_field :title %>
<p>Opinion</p>
<%= f.text_area :body %>
<br><%= f.submit 'Create Book', class: "btn btn-success" %></br>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= render 'layouts/error_messages', model: f.object %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
  <% end %>
<%= form_with model:@book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
<%= f.text_area :body %>
<br><%= f.submit 'Update Book',class: "btn btn-success" %></br>
<%= link_to "Show", book_path(@book) %>
<a href= "/books" >Back</a>
<% end %>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
    <div class="row">
    <div class="col-md-3">
<%= render 'books/list', user: @user, book: @book %>
</div>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>

<table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
          <th></th>
          <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
       <td>
           <%= link_to (book.user) do %>
            <span><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback:"no_image.jpg", size:"40x40"  %></span>
           <% end %>
        </td>
        <td>
            <span><%= link_to book.title, book_path(book.id) %></span>
        </td>
        <td>
           <span><%= book.body %></span>
        </td>
        <td><% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete do %>
        ♥<%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post do %>
        ♡<%= book.favorites.count %>
      <% end %>
    </p>
  <% end %></td>
      <td><% if current_user != book.user %>
        <% if book.user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(book.user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(book.user.id), method: :post %></p>
        <% end %>
    <% end %></td>
        <td><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></td>
      </tr>
        <% end %>
   </tbody>
</table>
</div>
</div>
</div

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
    <div class="row">
    <div class="col-md-3">
<%= render 'books/list', user: @user, book: @books %>
 </div>
 <div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
          <td>
              <span><%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback:"no_image.jpg", size:"40x40" %></span>
             <br>
              <%=link_to user_path(@user) do %>
              <p><%= @user.name %>
              <% end %>
              </p>
          </td>
          <td>
              <%=link_to book_path do %>
              <p><%= @book.title %>
              <% end %>
              </p>
          </td>
          <td>
              <p><%= @book.body %>
              <% if @user==current_user %>
              </p>
          </td>
          <td>
              <%= link_to "Edit", edit_book_path(@book),class: "btn btn-success" %>
              <%= link_to "Destroy", book_path(@book),class:"btn btn-danger", method: :delete,"data-confirm" => "本当に消しますか？" %>
               <% end %>
          </td>
          <td><% if @book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        ♥<%= @book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(@book), method: :post do %>
        ♡<%=  @book.favorites.count %>
      <% end %>
    </p>
  <% end %></td>
    </tr>
    </thead>
  </table>
  <div class="comments">
<p>コメント件数：<%= @book.post_comments.count %></p>
<% @book.post_comments.each do |post_comment| %>
  
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% if post_comment.user == current_user %>
  <div class="comment-delete">
    <%= link_to "削除", book_post_comment_path(post_comment.book, post_comment), method: :delete %>
  </div>
<% end %>
<% end %>
</div>
<div class="new-comment">
<%= form_with(model:[@book, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/homes/about.html.erb
<h1>welcome to <i class="fas fa-book"></i>Bookers!</h1>


<h4>CopyRight Infratop.inc</h4>

app/views/homes/top.html.erb
 <body>
   <main>
     <p id="notice"></p>
   <div class="container">
     <div class="row">
       <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
   <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
    <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
    </div>
    </div>
    </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href= "/">Bookers</a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <div class="navbar-nav ml-auto">

    <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user.id) do %>
        <i class="fas fa-home nav-link text-light">Home</i>
        <% end %>
        </li>
        <li>
           <%= link_to  user_registration_path do %>
         <i class="fas fa-users nav-link text-light">Users</i>
         <% end %>
         </li>
         <li>
           <%= link_to  books_path do %>
         <i class="fas fa-book-open nav-link text-light">Books</i>
         <% end %>
         </li>
         <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt nav-link text-light">logout</i>
        <% end %>
        </li>
      </li>
    <% else %>

        <h3 class="header-botton">

        <li>
          <%= link_to root_path do %>
          <i class="fas fa-home nav-link text-light">Home</i>
          <% end %>
        </li>
        <li>
           <%= link_to home_about_path do %>
        <i class="fas fa-link nav-link text-light">About</i>
        <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path do %>
        <i class="fas fa-user-plus nav-link text-light">sign up</i>
        <% end %>
        </li>
        <li>
        <%= link_to new_user_session_path do %>
       <i class="fas fa-sign-in-alt nav-link text-light">Login</i>
       <% end %>
      </li>
    <% end %>
    <%= flash[:notice] %>
    </div>
   </div>
    </div>
    </nav>
    </header>
  <%= yield %>
  </body>
  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</html>

app/views/post_comments/index.html.erb
<% @post_images.each do |post_image| %>
<div>
  <%= link_to post_image_path(post_image.id) do %>
    <%= attachment_image_tag post_image, :image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag('sample-author1.jpg') %></p>
  <p>本のタイトル：<%= post_image.book_title %></p>
  <p>本のオピニオン：<%= post_image.book_opinion%></p>
  <p>ユーザーネーム：<%= post_image.user.name %></p>
  <p><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %></p>
</div>
<% end %>

app/views/post_comments/show.html.erb
<div class="post-body">
  <%= attachment_image_tag @post_image, :image %>
  <p>本のタイトル：<%= @post_image.book_title %></p>
  <p>本のオピニオン：<%= @post_image.book_o %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
</div>

<div class="comments">
<p>コメント件数：<%= @post_image.post_comments.count %></p>
<% @post_image.post_comments.each do |post_comment| %>
  <p><%= image_tag('sample-author1.jpg') %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
<% end %>
</div>
<div class="comments">
<p>コメント件数：<%= @book.post_comments.count %></p>
<% @book.post_comments.each do |post_comment| %>
  <p><%= image_tag('sample-author1.jpg') %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% if post_comment.user == current_user %>
  <div class="comment-delete">
    <%= link_to "削除", post_image_post_comment_path(post_comment.book, post_comment), method: :delete %>
  </div>
  <% end %>
<% end %>
</div>
<div class="new-comment">
<%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
  <% end %>
<%= form_with model:@user, local:true do |f| %>
<div class="form-group">
  <label for="inputName">Name</label><br>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%><br>
</div>
<div class="form-group">
  <label for="inputImage">Image</label><br>
  <%= f.attachment_field :profile_image, placeholder: "image" %><br>
  </div>
  <div class="form-group">
  <label for="inputintroduction">Introduction</label><br>
   <%= f.text_area :introduction, autofocus: true, id:"introduction"%><br>
   </div>
   <div class="form-group">
  <%= f.submit "Update User", class: "btn btn-secondary" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/users/followers.html.erb
<h1>Users#followers</h1>
<p>Find me in app/views/users/followers.html.erb</p>

<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/follows.html.erb
<h1>Users#follows</h1>
<p>Find me in app/views/users/follows.html.erb</p>

<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
    <div class="row">
    <div class="col-md-3">
    <%= render 'books/list', user: @user, book: @book %>
    </div>
 <div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td>
                <span><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback:"no_image.jpg", size:"40x40" %></span>
            </td>
            <td>
                <span><%= user.name %></span>
            </td>
            <td>
                <span><%= link_to "Show", user_path(user.id) %></span>
            </td>
            <td><% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
        </div>

</div>
</div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
    <div class="row">
    <div class="col-md-3">
<%= render 'books/list', user: @user, book: @book %>
</div>
   <div class="col-md-8 offset-md-1">
 <section class="book">
   <h2>Books</h2>
   <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
   <div class="book-box"></div>
     <% @books.each do |book| %>
      <tr>
      <div class="book-item">
        <section class="book-text">
         <td>
          <%= link_to user_path do %>
          <span><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback:"no_image.jpg", size:"40x40" %></span>
          <% end %>
          </td>
         <td>
          <h3 class="book-title"><%= link_to book.title,book_path(book.id) %></h3>
          </td>
          <th>
          <p class="book-opinion"><%= book.body %></p>
          </td>
        </section>
      </div>
     <% end %>
      </tbody>
     </table>
  </section>
</div>
</div>